name: skapka_app
description: "Skapka - scout app to help parents sign up their children for events."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  auto_route: ^10.3.0
  dotenv: ^4.2.0
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  supabase_flutter: ^2.10.3
  gaimon: ^1.4.1
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.3
  icons_launcher: ^3.0.3
  device_preview: ^1.3.1
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  figma_squircle: ^0.6.3
  delightful_toast: ^1.1.0
  colorful_safe_area: ^1.0.0
  url_launcher: ^6.3.2
  intl: ^0.20.2
  flutter_speed_dial: ^7.0.0
  flutter_markdown_plus: ^1.0.7
  custom_sliding_segmented_control: ^1.8.5
  loader_overlay: ^5.0.0
  country_flags: ^4.1.1
  package_info_plus: ^9.0.0
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.6
  build_runner: ^2.10.4


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logos/
    - assets/images/app_icon/
    - assets/images/shapes/
    - assets/icons/
    - assets/icons/navbar/
    - assets/app_icon/
    - .env
  fonts:
    - family: TheMixC5
      fonts:
        - asset: assets/fonts/TheMixC5-4/TheMixC5-4_SemiLight.otf
          weight: 300
          style: normal
        - asset:  assets/fonts/TheMixC5-4/TheMixC5-4iSemiLightIta.otf
          weight: 300
          style: italic
        - asset:  assets/fonts/TheMixC5-4/TheMixC5-7_Bold.otf
          weight: 700
          style: normal
        - asset:  assets/fonts/TheMixC5-4/TheMixC5-7iBoldItalic.otf
          weight: 700
          style: italic
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 900
          style: normal