name: skapka_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  auto_route: ^10.3.0
  dotenv: ^4.2.0
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  supabase_flutter: ^2.10.3
  gaimon: ^1.4.1
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.3
  icons_launcher: ^3.0.3
  device_preview: ^1.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.6
  flutter_launcher_icons: ^0.12.0
  build_runner: ^2.10.4

icons_launcher:
  image_path: "assets/images/app_icon/app_icon_v1.png"
  platforms:
    android:
      enable: true
      image_path: "assets/images/app_icon/app_icon_v1.png"
      notification_image: "assets/images/app_icon/app_icon_v1.png"
      # adaptive_background_color: '#ffffff'
      adaptive_background_image: "assets/images/app_icon/app_icon_v1.png"
      adaptive_foreground_image: "assets/images/app_icon/app_icon_v1.png"
      adaptive_round_image: "assets/images/app_icon/app_icon_v1.png"
      adaptive_monochrome_image: "assets/images/app_icon/app_icon_v1.png"
    ios:
      enable: true
      image_path: "assets/images/app_icon/app_icon_v1.png"
      # For iOS 18+ (support dark and tinted)
      dark_path: "assets/images/app_icon/app_icon_v1.png"
      tinted_path: "assets/images/app_icon/app_icon_v1.png"



flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logos/
    - assets/images/app_icon/
    - assets/icons/
    - assets/app_icon/
    - .env
  fonts:
    - family: TheMixC5
      fonts:
        - asset: assets/fonts/TheMixC5-4/TheMixC5-4_SemiLight.otf
          weight: 300
          style: normal
        - asset:  assets/fonts/TheMixC5-4/TheMixC5-4iSemiLightIta.otf
          weight: 300
          style: italic
        - asset:  assets/fonts/TheMixC5-4/TheMixC5-7_Bold.otf
          weight: 700
          style: normal
        - asset:  assets/fonts/TheMixC5-4/TheMixC5-7iBoldItalic.otf
          weight: 700
          style: italic
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf